### PR TITLE
Help improving shoesrb website design

### PR DESCRIPTION
**Pull request by wpp**
The homepage now contains 4 major pages:
- The landing/home page.
- Contributers page for people interested in contributing.
- Tutorials page for people interested in learning Shoes.
- Blog

contribute
tutorials
blog

**The About page is empty for now** but would be great to have some information
about Shoes here.

Additional Note: The **texts for the page are not that great.** Partly because
I had English as a second language in school :) So improvements are welcome.
Also: The background images (and header of tutorials page) are taken from
Nobody Knows Shoes, I thought it would be nice to have a bit of __why_ on the
site. :heart:

### CODE REVIEW

**Comment by jrgifford** [comment]
The _only_ problem (and I mean the only problem) I have with this is that it's very image-heavy, and that the images are high-quality.

Other than that, great job! Does anyone know how we could shrink these images down to something so it won't take forever to load on a 1MBsDown/512KBsUp connection? I've never done anything like it before...

**Comment by wpp** [comment]
Good point. Totally forgot about that. I'll try making these images smaller give you some numbers then.

**Comment by PragTob** [comment]
Looks awesome thanks!

**Comment by davorb** [comment]
I like what you've done with the site, but here are a few things that we might want to look into.
1. We need to change the colour scheme.
2. The contribute page is an awesome idea, but i'm kind of annoyed that the box with users doesn't have the same margin-right as margin-left. It looks a bit weird.
3. We should use CDNs to speed things up. Perhaps put the entire site on Amazon S3 and make use of CloudFront?
4. What does the first page look like? What we want is something with a big "Get Shoes4"-button and then below that perhaps something that shows why Shoes is so great. Sort of like the [JRuby](http://jruby.org/), [Ruboto](http://ruboto.org/) or [Rubinius](http://rubini.us/) sites.

**Comment by steveklabnik** [comment]
With the number of requests that we get, CDNs/CloudFront is simply not necessary.

**Comment by steveklabnik** [comment]
Why do we need to change the color scheme?

**Comment by wpp** [comment]
- @davorb I especially agree with Point 4. The home page should have a download button/link. And I really like rubnius' little snippets on how to get started. When you say "why shoes is great" do you mean text?
- I feel like "color scheme" is a pretty hard problem (in general) and I'm not a designer.
- Point 2: Ha, now that you mentioned it, I cannot unsee and it shall be fixed :pray:

**Comment by davorb** [comment]
Yes, you're right about the CDN.

But not even changing the twitter bootstrap-black bar at the top just 

## feels lazy. So I think that we should at least change that.

Davor Babic
davor@davor.se

Steve Klabnik wrote:

**Comment by steveklabnik** [comment]
Absolutely nobody except the most hardcore of nerds knows anything about Bootstrap. I show people the default black bar all the time, and they think it's gorgeous.

That said, I'm also partial to black. ;)

**Comment by jrgifford** [comment]
plus, we can get shoes featured on http://builtwithbootstrap.com/ !! :metal:

## 

James Gifford
cell: 2162238574

**Comment by wpp** [comment]
Hey guys! Sry but I've been busy, however shoesrb.com shall not be forgotten!

To reduce the image size I converted the biggest images to jpg and lowered the quality. I also combined some of them into things called "sprites" :)

### Before:

zsh-1

### Now:

zsh 2

### Contributors are centered now :)

Screen Shot 2013-01-22 at 10 18 17 PM

Lemme know what ya'll thinkin :hamburger:

**Comment by davorb** [comment]
Nice! :-)

If you look at the white box that the red shoes logo is floating in, you will notice that it sticks out more to the left than the gray box does. You might want to fix that.

**Comment by wpp** [comment]
@davorb you sir got some eagle eye vision going on :+1: fixed it.

**Comment by steveklabnik** [comment]
Merging! I like what's here so far.

I would like to update the site ASAP, as the old shoes-web is running 2.3.5, which has some security holes. This one should not. :)

**Comment by steveklabnik** [comment]
... so I guess what I'm saying is that I might push this up, because it's Good Enough, and if we find another few small things we can keep tweaking them. :)

**Comment by steveklabnik** [comment]
Yep! I'm deploying this now, looks great so far :D

**Comment by steveklabnik** [comment]
It's live: http://shoesrb.com

**Comment by jrgifford** [comment]
:+1: looks good!

**Comment by wpp** [comment]
Awesome :+1:

**Comment by wpp** [comment]
Totally forgot: https://www.youtube.com/watch?v=hmbUNF1Q4R8

**Comment by nbouhid** [comment]
Sorry to interrupt guys, but I have to ask you something. Why did you delete the downloads section??

**Comment by steveklabnik** [comment]
One issue with downloads is that GitHub is not hosting binary stuff any more, so I have to move them to my s3 bucket and create a redirect on the site. @nbouhid this is a bug, mind opening another ticket, since you discovered it?!

**Comment by wasnotrice** [comment]
@steveklabnik I'm going to be putting up some packaging files on S3 too. Is there any reason not to use our personal buckets?

**Comment by wasnotrice** [comment]
Plus, new design: :metal:

**Comment by steveklabnik** [comment]
I don't think so, other than committing to keeping them up.

**Comment by davorb** [comment]
First of all, the site looks great! greeeaat

Here's a couple of more thoughts.
https://www.dropbox.com/s/jro5ifzsihvgdz0/Screen%20Shot%202013-01-30%20at%208.13.20%20AM.png

https://www.dropbox.com/s/27wawpzwu9kwq00/Screen%20Shot%202013-01-30%20at%208.19.15%20AM.png

I'm not sure what the icons would look like if we made them stick "up" instead of "down" (or if it would even be an improvement). But you might want to try it out and see what it looks like.

In any case. The site looks great and I'm just nitpicking.

**Comment by ashbb** [comment]
@wpp @steveklabnik and folks Awesome!! I LOVE new Shoes site. Great work, thanks!

The following is my two cents. ;-)
- There is a button named "Read the blog >>" on top page. But it links to the `contribute` page. Is this right?
- The Manual link on Tutorials page is broken.
- About the Shoes Blog page. Who can post?
- About Contribute page. We merged Brown Shoes and Purple Shoes into Shoes 4. So, IMHO, the Brown Shoes link may not be necessary any more.
- About the Shoes Team. There are only 10 members on Contribute page. But I think there are more people contributed to Shoes. Oh, @wpp is not listed!
- How about adding a link to Shoes ML on "About" page?

**Comment by steveklabnik** [comment]
1. I will fix that now.
2. I just fixed it
3. Anyone who submits one! There is a rake task which makes a new post, you write it in markdown, commit, and send a PR. :smile: 
4. Good idea.
5. Yep! this should get improved
6. Sounds good, I will do that now too.

If anyone wants to tackle 4 or 5, feel free!

**Comment by steveklabnik** [comment]
Actually, I'll remove the brown shoes link too.

I'm going to add the ML on the 'contribute' page too.

Also, the about page could use some improvements!

**Pull request merged**
