### PR TITLE
Update About page

### PR DESCRIPTION
**Pull request by garciadanny**
https://github.com/shoes/shoesrb.com/pull/20, https://github.com/shoes/shoesrb.com/issues/17

Hello everyone, I'm a [gSchool](http://gschool.it) student currently learning Rails and new to open source. I updated the about page and would really appreciate some feedback and suggestions to make it better. Thanks.

### CODE REVIEW

**Comment by garciadanny** [comment]
I pretty much grabbed info from the Shoes [README](https://github.com/shoes/shoes/blob/develop/README.md) and @steveklabnik's [blog post](http://blog.steveklabnik.com/posts/2012-05-25-shoes-4-work-is-starting--get-involved) about Shoes 4.

**Comment by ashbb** [comment]
@danny-g Fantastic! :+1:

**Comment by wpp** [comment]
Awesome thank you @danny-g

**Comment by steveklabnik** [comment]
Thank you so much, Danny!

**Comment by davorb** [comment]
Much obliged. :+1:

**Pull request merged**
