### PR TITLE
removes the team.jpg image and uses code instead!

### PR DESCRIPTION
**Pull request by eliduke**
This seemed like a easy intro into helping out with shoes. I hope you like what I did!

### CODE REVIEW

**Comment by PragTob** [comment]
OH MY GOD I WANTED TO HAVE THIS FOR SUCH A LONG TIME THANK YOU VERY MUCH YES I KNOW I'M ON CAPSLOCK I'M JUST SUPPER EXCITED =D :+1: :fireworks: 

I'll leave this tab open until I got some other urgent work done will review :)

**Comment by jasonrclark** [comment]
Agreed! Ran this locally and looks great to me. :sparkling_heart: And now maybe I can get on the team member list! :grin: 

On that note, here's a few folks that have been active lately, and should get on the list:
- https://github.com/ccoupe
- https://github.com/KCErb
- https://github.com/jasonrclark

So. Much. Awesome:exclamation::exclamation::exclamation:

**Comment by PragTob** [comment]
Filed a PR for your PR, because well that's still a bit hard some times. I could also merge it instantly.

Couple of things: @ccoupe @KCErb @jasonrclark should definitely be added, if they don't object.

Similarly there are a couple of folks I haven't heard from in a long, long time...  I think when we made the website it was like everyone with a commit gets to be on the page.

So, I don't want to hurt any feelings here or something like that (and I don't think I do) but I'd remove a couple of folks that made a couple of commits when the project started but then moved on afterwards (which is totally fine). That'd be alindemann, ychatz and nashby.

Peter and James are still around (upon request), and well peter layed out all the foundations we are working on these days :)

What do you think?

Cheers,
Tobi

**Comment by jasonrclark** [comment]
Seems reasonable here. Could also link the contribution page on the repos for the full list of everyone who has helped.

**Comment by PragTob** [comment]
Yeah, I'd love links to shoes/{shoesrb.com, shoes, shoes4} - great idea! We could also have a page/section that just pulls in everyone from all shoes org repos, aggregates their stats and then sorts them by random/commit/whatever... ot just name. Or whatever.

That's be sweet, but nothing necessary - maybe something for a hack day/hack evening :)

**Comment by jasonrclark** [comment]
Agreed, totally a task for another day, but would be rad to generate off the GitHub API someday.

For now happy to :shipit: with @pragtob's fix and maybe adding those other names. :heart:

**Comment by eliduke** [comment]
Sounds great, y'all. I removed older team members and added new ones.

**Comment by PragTob** [comment]
Seems great, thanks a bunch for your work! =)

**Comment by wpp** [comment]
I think this closes #7 as well. Thanks @eliduke

**Comment by PragTob** [comment]
Yeah I'll close it thanks for the hint Philipp! Will oprn a new one, though for automated retrieval/showcase.

**Comment by JesseHerrick** [comment]
I posted a solution over at #72.

**Pull request merged**
