### PR TITLE
Reorganize homepage layout

### PR DESCRIPTION
**Pull request by mariosant**
I have pulled the homepage hero banner to the top while pushing the shoes description under that. I believe it enhances the message that shoes is damn too easy and usable framework.

Let me know what you think.

### CODE REVIEW

**Comment by wpp** [comment]
Thanks! Could you perhaps put the css in one of the existing stylesheets? Then we don't have to include another one.

**Comment by mariosant** [comment]
Done! I have squashed the commits into one, for cleaner history.

**Comment by jasonrclark** [comment]
Hey @qboss, sorry this didn't get dealt with back when you did the work. It looks like things have moved on enough it doesn't merge cleanly, and there's an upcoming revamp of the site's look and feel underway over on #52.

Were you interested in bringing this up to date with the current `gh-pages` tip? If so, I'd be happy to see about integrating things until the new design arrives.

Again, sorry we dropped the ball here :frowning: but appreciate your work on it.

**Comment by mariosant** [comment]
I am happy to help Jason, if help is needed!

Yes I am interested in that! You will hear more from me soon!

## 

Marios Antonoudiou

**Comment by mariosant** [comment]
@jasonrclark good to go.

**Comment by mariosant** [comment]
@jasonrclark sorry, this one got done in a hurry hold this PR until further notice please.

**Pull request closed without merging**
