### PR TITLE
Add Get Help page

### PR DESCRIPTION
**Pull request by jamesaanderson**
Adds #21

### CODE REVIEW

**Comment by steveklabnik** [comment]
Awesome. Thanks so much!

**Comment by jamesaanderson** [comment]
@steveklabnik By the way, there's an Application Error on http://shoesrb.com. Hope I didn't break anything.

**Comment by steveklabnik** [comment]
Oh no!

I didn't deploy yet, so it wasn't you.

**Comment by steveklabnik** [comment]
It's back! we didn't have a web process running :cry:

**Comment by jamesaanderson** [comment]
Oh good

**Pull request merged**
