### PR TITLE
Update for 3.2.15

### PR DESCRIPTION
**Pull request by ccoupe**
Update to Shoes 3.2.15

BTW, I'm seeing a decent amount of downloads for all Shoes 3.2 archs with shoesrb.com as the referer.  Hard to say if they are happy downloaders or real people but it's more than I expected.

### CODE REVIEW

**Comment by KCErb** [comment]
That's great! You're doing a great work keeping Shoes 3 going! I think a big part of the attraction of Shoes to new-programmers is packaging apps, so it's really great to have a working version that does that while we try to get Shoes 4 off the ground.
Keep it up @ccoupe! :+1:

**Comment by jasonrclark** [comment]
Super cool to see Shoes 3 keep moving on! Thanks @ccoupe!

Was double-checking the links and the first three (Linux + Rasp Pi) are all giving me a 404. Any idea what's up there before getting this merged?

Thanks!

**Comment by ccoupe** [comment]
Jason, thanks to double checking. I think I've got the commit and pull fixed or may its a second pull.
I changed the Linux file names from .run to .install and forgot to update that in the download.html

**Comment by jasonrclark** [comment]
Looks good to me. :ship:

**Comment by jasonrclark** [comment]
That's all merged and looks good. Noticed when poking the site after that this link appears broken:

<a href="http://shoes.mvmanila.com/federales/">(see here for what's new)</a>

Where's that supposed to point @ccoupe?

**Pull request merged**
