### PR TITLE
Fixed for Shoes 4 and Ruby changes

### PR DESCRIPTION
**Pull request by snood1205**
There were some method calls in the walk through that are not compatible with shoes 4. Additionally, `Range#rand` is a private method now and will throw an exception. I replaced all of the `Range#rand` calls with `Kernel#rand(Range)` which is the way to call it now.

### CODE REVIEW

**Comment by jasonrclark** [comment]
Thank you! Totally happy with the rand fixes but I suspect the incompatiblilties are actually bugs against Shoes 4. I'll verify tomorrow but if that's the case, we'll get those fixed up so the existing tutorial code just works. :sparkles:

**Comment by snood1205** [comment]
The "incompatibilities" were mostly methods that took an options hash going to be more implicit. For example `arrow(top: 0, left: 0, width: 40)` turned into `arrow(0, 0, 40)`.  Where the parameters for arrow are `arrow(top, left, width)`

**Comment by PragTob** [comment]
@snood1205 which is an API that we definitely want to support so it really is more of a shoes4 bug :) We support left/top/width and others for other elements so I suspect it's just an incomplete arrow implementation :)

**Comment by snood1205** [comment]
@PragTob Alright! Let me revert those back to what they were and just keep the random fixes in.

**Comment by snood1205** [comment]
@PragTob I reverted the hash incompatibilities. There was one more change on line 342 where `link` changed from being a chained `link(str)#click` to `link(str, &blk)` in Shoes 4. I was wondering if that was intended or a bug as well. I kept it as the new `link(str, &blk)` instead of the chained `link#click` as it was in Shoes 3, but I can change it backed to the chained invocation if desired.

**Comment by jasonrclark** [comment]
Thanks for the revert @snood1205! Tested it out this morning, and indeed I think the `link` stuff is also a regression in Shoes 4 so I've entered it as https://github.com/shoes/shoes4/issues/1334 over there.

These are great finds as we really want Shoes 4 to happily run any existing Shoes 3 program. Thank you for suggesting the changes!

**Comment by PragTob** [comment]
Thanks! I think the `link(...).click` is also a regression :)

**Comment by snood1205** [comment]
Alright well it's now back to a form where there is no regression adaption and solely the rand changes. A list of the regressions found were:
- `star` going from `star(opts = {})` to `star(top, left, points)`
- `oval` going from `oval(opts = {})` to `oval(top, left, radius)`
- `link` going from the chained `link#click` to `link` with a block parameter.

**Comment by jasonrclark** [comment]
Sweet thanks! Did oval have the problems too? I'm thinking I'll just double check all the art methods over in Shoes 4 to ensure they're lined up.

**Comment by snood1205** [comment]
@jasonrclark I was looking at shoes-core/lib/shoes/dsl.rb and it seems like the issue for `oval` is that on line 367 you have `OVAL_ALLOWED_ARG_SIZES = [0, 3, 4].freeze` but because the method definition is `oval(*args, &blk)` if `oval` is invoked like `oval(top: 10, left: 30, radius: 4)` `args.size` will return `1` because `args` is `[{top: 10, left: 30, radius: 4}]`. Either you would want to check `args[0].size` or add `1` to `OVAL_ALLOWED_ARG_SIZES` so then it would be `OVAL_ALLOWED_ARG_SIZES = [0, 1, 3, 4].freeze`. That at least to me seemed like the problem.

**Pull request merged**
