### PR TITLE
Update downloads.html to include Shoes 3.2

### PR DESCRIPTION
**Pull request by ccoupe**
Add links for Shoes 3.2 - Hopefully I didn't make any mistakes.

### CODE REVIEW

**Comment by KCErb** [comment]
I think this is awesome! I just tried a quick example app on 3.2 and everything looks great! Thanks a ton Cecil!

**Comment by ccoupe** [comment]
Ping-  pull request

**Comment by PragTob** [comment]
Sorry I'm a bit busy with my master's thesis atm which should be done soon, will do it afterwards but happy if anyone else picks this up.

Thanks for the ping.

**Comment by jasonrclark** [comment]
I'm happy to review and merge, but I have no idea how to actually deploy the site and/or if I have rights to do that.

**Comment by JesseHerrick** [comment]
@jasonrclark if you have push rights, then GitHub Pages will automatically build it for you. As long as you merge with the `gh-pages` branch.

**Comment by PragTob** [comment]
@jasonrclark you should have ALL THE RIGHTS :-) Thanks for picking this up.

**Comment by jasonrclark** [comment]
:shipit: Thanks @ccoupe for the updates, and apologies I didn't realize sooner that I had the rights to push this up for you!

**Comment by PragTob** [comment]
:+1: Thanks @jasonrclark

**Comment by ccoupe** [comment]
Thanks. You probably want to revert back to the Red Shoes icon and remove the Shoes 3.2 blog reference at the top of the home page. Those exist at my private copy but probably don't mean much to Red Shoes  Home page.

**Comment by jasonrclark** [comment]
@ccoupe Good point. Will do that as soon as I can get around--maybe this evening. Thought I'd give the other shoes (icon) a try for a bit :)

**Comment by jasonrclark** [comment]
Done! Definitely let me know if you see any other tweaks or additions with coming Shoes 3.x stuff @ccoupe and I'm happy to help make that happen.

**Comment by ccoupe** [comment]
Thank you again. The only change from me in the future is for download.html to reflect new tiny version numbers. I'd like to close half the bug reports but that's a different site.

**Pull request merged**
