### PR TITLE
Use FontAwesome for ALL! the icons

### PR DESCRIPTION
**Pull request by nathancarnes**
Since FontAwesome is getting loaded up anyway, we can ditch a few images and clean up a bunch of CSS by implementing it throughout the site. 

At some point down the road it would be good to update FontAwesome to a newer version, but it probably makes sense to tackle that at the same time as upgrading Bootstrap.

### CODE REVIEW

**Comment by jasonrclark** [comment]
I really like the updated look with that!  I'm in favor of a merge. @PragTob @wasnotrice?

A few before and after's for anyone who doesn't want to pull it down to run themselves.

**Bottom of homepage**
Before:
image

After:
image

**Downloads**
Before:
image

After:
image

**Comment by nathancarnes** [comment]
@jasonrclark thanks! I should have added the before/afters.

Depending on the timing of #52, I'd also be willing to tackle upgrading Bootstrap + FontAwesome, which should also resolve #13.

**Comment by wasnotrice** [comment]
Love it!

**Comment by PragTob** [comment]
Font Awesome is awesome, totally pro on this one! So yeah! :+1: :-D

**Comment by wpp** [comment]
Looking good!

**Comment by jasonrclark** [comment]
:boom:

**Comment by jasonrclark** [comment]
Thanks again @nathancarnes for that! If you're interested in upgrading Bootstrap + FontAwesome, it sounds over on #52 like that probably isn't moving quickly. @wpp expressed some interest over there too, so you might coordinate with him about any changes so we don't get any duplicate/overlapping work.

Appreciate everyone pitching in to improve the site so much! :heart:

**Comment by nathancarnes** [comment]
@jasonrclark I'll check in over there and see how I can make myself useful. :heart:

**Comment by PragTob** [comment]
Thanks @nathancarnes ! :+1:

**Pull request merged**
