### PR TITLE
Two small formatting fixes...

### PR DESCRIPTION
**Pull request by nicholalexander**
I found a div that was closed too soon which made the facebook panel not align correctly so I fixed that.

Also, there were some alignment problems with the download arrow which can be solved nicely by just using bootstrap instead of a the fixed height.  Using the columns keeps all the downloads nicely aligned all the way down instead of bumping back in.

### CODE REVIEW

**Comment by jasonrclark** [comment]
Facebook panel fix looks 👌 to me.

On the download, it looks like this for me on Chrome and Safari:

image

Seems like the icon's a little off... what's it look like for you @nicholalexander?

**Comment by nicholalexander** [comment]
looks the same for me.  i aligned it on the shoes title, but maybe that's what looks wierd?

here's a screenshot of the two columns without a spacer - i think it looks too mushed, what do you think?
screen shot 2017-12-01 at 8 44 57 am

also, it looks like it was off by one pixel anyway, so i changed that, in case that's what the issue was!

**Comment by jasonrclark** [comment]
Hmm, does look a little smushed there, but I think I was noting that the Shoes title over the icon is way over on the left for my view, which ends up looking odd. Maybe it should just be placed above and aligned with the list of versions to download?

**Comment by nicholalexander** [comment]
like this?

screen shot 2017-12-04 at 12 03 40 pm

**Comment by jasonrclark** [comment]
Hmm, I think I was thinking the Shoes lined up over the logo, both of which were directly over the list. Sorry to be picky about this... just looks a bit funny where things are at the moment.

**Comment by nicholalexander** [comment]
no worries!  i wish i had a better eye for this.  ok, fixed it.  maybe!  how's it look now?

screen shot 2017-12-07 at 9 47 52 am

**Comment by jasonrclark** [comment]
Cool cool. Thanks @nicholalexander!

**Pull request merged**
