### PR TITLE
Add permalinks without .html suffix and fix deprecated config option.

### PR DESCRIPTION
**Pull request by JesseHerrick**
Just a small fix, but I've never liked .html in my permalinks. I've also changed `name` from the default to `Shoes` and `pygments: true` to `highlighter: pygments`.

### CODE REVIEW

**Comment by JesseHerrick** [comment]
This is kind of a part of #52. Also, here are the new routes:

```
/downloads.html => /downloads/
/tutorials.html => /tutorials/
/blog.html => /blog/
/contribute.html => /contribute/
/about.html => /about/
/get_help.html => /help/
```

**Comment by jasonrclark** [comment]
Definitely like using the non-`.html` style for the links. :+1: on that!

This looks like the PR pulled in a lot of other CSS changes beyond your description. Was that intended?

Haven't read through all of them in detail but I'm betting a few conflict with the Bootstap+FontAwesome PR @nathancarnes put up on #59 (which I was considering getting merged fairly soon). Any thoughts on how best to proceed there?

**Comment by JesseHerrick** [comment]
Oh, my bad @jasonrclark. I've been working away at the new design. I only meant to PR bcf410296ecc9fafb84503f701d42aad4e0c5ddc. The design changes I made are not ready.

**Comment by JesseHerrick** [comment]
I'm going to close this PR, cherry pick the proper changes into a new branch and then PR again.

**Pull request closed without merging**
