### PR TITLE
Community and Contributor Pages Built From Github

### PR DESCRIPTION
**Pull request by nicholalexander**
Addressing #72 - This is a script to build a few YAML data files using the github API and then use those data files to display the core team as well as the larger community.

Relevant files are `lib/build_contributors_data.rb` and changes to `contributor.html`.  Result is:

screen shot 2017-12-18 at 12 52 26 pm

If this looks like it's going in the right direction, we should figure out:

* how often you want to build the data
* if we want to build it manually via `ruby build_contributors_data`
* how we use the github authorization - there are a sufficiently high number of api calls as to require auth, so we could use a .env file or I can just put my token in the repo?
* if we want to remove the old team images or no
* there's also more data than we actually need to render that page because I was trying to get contribution counts to which repos with the idea that might be useful - we can easily pare it back to just get what we use to render that page.

Also, I think it's worth it to rethink the wording of the community section as I think its a particularly important area to help encourage people.  My little place holder text doesn't live up to this requirement!

Todos:
- [x] Fix the Readme with instructions of building
- [x] Delete image files?
- [x] Token

Thanks!

### CODE REVIEW

**Comment by jasonrclark** [comment]
Thanks for working on this @nicholalexander! Definitely a good step forward.

Couple thoughts.

1) Totally in favor of allowing specifying the GitHub token via an ENV variable or .env file or something like that.
2) I'm fine with it being a manual script that we run that modifies contents, and we can just do it periodically. Setting something up automated seems unnecessary given the activity level in the community.
3) Biggest revision I can see is I'd like to reconsider the members vs others way the data's gathered... For whatever org structure reasons, some folks who have been very active on shoes3 only show up as community members.

    What do you think about just counting contributors with a certain commit count across the org's repos, and just having a single section with those?

**Comment by nicholalexander** [comment]
great! will set up dotenv, keep it manual, and refactor so that it's just by contribution counts to each repo in the shoes org.  I'll also take a stab at the language to reflect that and to encourage other contributions.

n

**Comment by nicholalexander** [comment]
so this version just has all the contributors in one big section sorted from the highest number of contributions on down.  it might be too big?  what would you suggest the cut off for contributions is?  

the other way to do it is to switch it around and have the ways to contribute at the top and then all the contributors at the bottom and not cap it off so that you can include even people who have one contribution - which I think is more inclusive?  we could also split it, so the top 12 contributors are at the top and then the rest are below?

screen shot 2018-01-08 at 12 55 26 pm

**Comment by jasonrclark** [comment]
Oh, I think I like the idea of putting the text and directions about getting involved first, then showing the contributors after that. If that doesn't totally wreck the loading time for the page showing everyone, that'd be rad!

**Comment by nicholalexander** [comment]
here're two versions, i'm partial to the second one - with everything stacked.  i took out the jumbotron because i thought the shading looked weird.  what do you think?

also, i got smaller versions of the avatar so that improves the page load time, i think it seems decent as it is and testing it on 3g speeds with no cache, it's about 2s for first paint, which i think is reasonable.

screen shot 2018-01-09 at 11 22 23 am

screen shot 2018-01-09 at 11 34 07 am

**Comment by jasonrclark** [comment]
@nicholalexander That looks great to me. I agree, I like the stacked (second) version, and the removal of the jumbotron here is just fine by me.

I'd say we can finally remove the strike-through text under the mailing list too to save a bit of vertical space.

**Comment by nicholalexander** [comment]
@jasonrclark done!

**Comment by jasonrclark** [comment]
Pulled this locally, and it looks excellent? You ready for the merge @nicholalexander

**Comment by nicholalexander** [comment]
yes, ready for the merge, thanks @jasonrclark!

**Pull request merged**
