### PR TITLE
Use FontAwesome icons instead of images.

### LINKED ISSUE #35: Operating System signs
Hi everyone,

Right now we got 4 signs for operating systems, 2 of them are Mac OSX. Can't we take a generic symbol for Mac OSX?

Plus the Linux one is Ubuntu, how about a cute little Tux?

Any ideas or objections? :-)

### PR DESCRIPTION
**Pull request by JesseHerrick**
Using FontAwesome icons makes the logos more customizable and responsive. They have a slight darken affect on hover, and link to the downloads section. To change the color of them, use the class `.os` in `shoes.css` (line 28). I made them responsive and change size as the window gets smaller. This should fix [issue #35](https://github.com/shoes/shoesrb.com/issues/35).

### CODE REVIEW

**Comment by PragTob** [comment]
i really like this, would like to wait for additional feedback before merging though ( @wpp @steveklabnik )

Also it says "Attribution is no longer required as of Font Awesome 3.0 but is much appreciated: "Font Awesome by Dave Gandy - http://fontawesome.io". " - so I'd like to add some attribution somewhere :-)

**Comment by PragTob** [comment]
Oh yeah and thanks a lot for tackling this! =)

**Comment by steveklabnik** [comment]
Sure, I'm :+1:

**Comment by JesseHerrick** [comment]
Alright, sounds good @PragTob. Do you want me to add the attribution myself? In the footer perhaps?

**Comment by wpp** [comment]
@JesseHerrick Thank you looks great! And yeah footer sounds find to me.

**Comment by PragTob** [comment]
Thanks for the work @JesseHerrick and thanks for the quick feedback @steveklabnik and @wpp - I'm hitting merge! =)

**Pull request merged**
